import { DashboardState } from './dashboard.types';

export const mockDashboardData: DashboardState = {
  metrics: {
    totalIncidents: 142,
    criticalIncidents: 3,
    escalations: 5,
    departmentsActive: 4,
    pendingDecisions: 12,
  },
  health: {
    activeIncidents: 45,
    resolvedToday: 28,
    averageResponseTimeMinutes: 42,
    healthScore: 78,
  },
  priorityQueue: [
    {
      id: 'INC-10023',
      title: 'Major Water Main Break - Downtown',
      category: 'Infrastructure',
      priority: 'CRITICAL',
      department: 'Water Management',
      status: 'PENDING',
      timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
      confidence: 0.95,
    },
    {
      id: 'INC-10024',
      title: 'Traffic Signal Failure at Main St Intersection',
      category: 'Traffic',
      priority: 'CRITICAL',
      department: 'Traffic Control',
      status: 'ASSIGNED',
      timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      confidence: 0.88,
    },
    {
      id: 'INC-10025',
      title: 'Fallen Tree Blocking Emergency Route',
      category: 'Environment',
      priority: 'HIGH',
      department: 'Parks & Forestry',
      status: 'PENDING',
      timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
      confidence: 0.91,
    }
  ],
  liveIncidents: [
    {
      id: 'INC-10026',
      title: 'Pothole on 5th Ave',
      category: 'Roads',
      priority: 'LOW',
      department: 'Public Works',
      status: 'PENDING',
      timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
      confidence: 0.82,
    },
    {
      id: 'INC-10023',
      title: 'Major Water Main Break - Downtown',
      category: 'Infrastructure',
      priority: 'CRITICAL',
      department: 'Water Management',
      status: 'PENDING',
      timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
      confidence: 0.95,
    },
    {
      id: 'INC-10022',
      title: 'Graffiti on Public Library',
      category: 'Vandalism',
      priority: 'LOW',
      department: 'Facilities',
      status: 'ASSIGNED',
      timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
      confidence: 0.89,
    },
    {
      id: 'INC-10020',
      title: 'Streetlight Outage in Residential Area',
      category: 'Utilities',
      priority: 'MEDIUM',
      department: 'Public Works',
      status: 'IN_PROGRESS',
      timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
      confidence: 0.93,
    },
  ],
  decisions: [
    {
      id: 'DEC-501',
      incidentId: 'INC-10023',
      incidentTitle: 'Major Water Main Break - Downtown',
      priority: 'CRITICAL',
      recommendedAction: 'Dispatch emergency repair crew immediately and cordon off affected streets.',
      responsibleDepartment: 'Water Management',
      confidence: 0.95,
      status: 'PENDING_REVIEW',
      timestamp: new Date().toISOString(),
      reasonSummary: 'High water volume reported near electrical substation. Risk of critical infrastructure damage.',
      evidenceWeightings: [
        { factor: 'Proximity to Substation', weight: 45 },
        { factor: 'Reported Water Volume', weight: 35 },
        { factor: 'Historical Pipe Age', weight: 20 },
      ],
    },
    {
      id: 'DEC-502',
      incidentId: 'INC-10024',
      incidentTitle: 'Traffic Signal Failure at Main St',
      priority: 'CRITICAL',
      recommendedAction: 'Deploy traffic wardens and schedule urgent electrical repair.',
      responsibleDepartment: 'Traffic Control',
      confidence: 0.88,
      status: 'APPROVED',
      timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      reasonSummary: 'High traffic intersection during rush hour causing severe congestion.',
      evidenceWeightings: [
        { factor: 'Traffic Volume (Rush Hour)', weight: 50 },
        { factor: 'Intersection Type', weight: 30 },
        { factor: 'Accident Risk', weight: 20 },
      ],
    }
  ],
  timeline: [
    {
      id: 'EV-1',
      incidentId: 'INC-10023',
      type: 'REPORTED',
      title: 'Incident Reported',
      description: 'Multiple citizens reported massive water leak.',
      timestamp: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    },
    {
      id: 'EV-2',
      incidentId: 'INC-10023',
      type: 'AI_ANALYSIS',
      title: 'AI Analysis Complete',
      description: 'Incident categorized as Critical Infrastructure hazard.',
      timestamp: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    },
    {
      id: 'EV-3',
      incidentId: 'INC-10023',
      type: 'DECISION',
      title: 'Decision Recommendation Generated',
      description: 'Recommended immediate dispatch of Water Management crew.',
      timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    }
  ],
  departments: [
    {
      id: 'DEP-1',
      name: 'Water Management',
      openCases: 12,
      criticalCases: 2,
      workload: 'HIGH',
      availabilityPercentage: 15,
    },
    {
      id: 'DEP-2',
      name: 'Public Works',
      openCases: 45,
      criticalCases: 0,
      workload: 'OPTIMAL',
      availabilityPercentage: 65,
    },
    {
      id: 'DEP-3',
      name: 'Traffic Control',
      openCases: 8,
      criticalCases: 1,
      workload: 'LOW',
      availabilityPercentage: 80,
    },
    {
      id: 'DEP-4',
      name: 'Parks & Forestry',
      openCases: 18,
      criticalCases: 1,
      workload: 'OPTIMAL',
      availabilityPercentage: 45,
    }
  ],
  trends: [
    { date: 'Mon', count: 24 },
    { date: 'Tue', count: 18 },
    { date: 'Wed', count: 35 },
    { date: 'Thu', count: 28 },
    { date: 'Fri', count: 42 },
    { date: 'Sat', count: 15 },
    { date: 'Sun', count: 12 },
  ],
  categoryDistribution: [
    { category: 'Infrastructure', percentage: 35 },
    { category: 'Traffic', percentage: 25 },
    { category: 'Sanitation', percentage: 20 },
    { category: 'Environment', percentage: 15 },
    { category: 'Other', percentage: 5 },
  ],
  primaryRecommendation: 'Focus resources on Water Management due to critical downtown main break and low department availability.',
};
